--liquibase formatted sql

--changeset vloisel-aogier:1

CREATE TABLE VOTE (
  ID BIGINT AUTO_INCREMENT,
  BAGGER_NAME VARCHAR(200) NOT NULL,
  SESSION_TITLE VARCHAR (4000) NOT NULL,
  USER_NAME VARCHAR (200) NOT NULL
);
ALTER TABLE VOTE ADD CONSTRAINT PK_VOTE PRIMARY KEY (ID);
ALTER TABLE VOTE ADD CONSTRAINT UNIQUE_VOTE UNIQUE (BAGGER_NAME, SESSION_TITLE, USER_NAME);

CREATE TABLE ACHIEVED_SESSION (
  ID BIGINT AUTO_INCREMENT,
  BAGGER_NAME VARCHAR(200) NOT NULL,
  TITLE VARCHAR (4000) NOT NULL,
  ACHIEVEMENT_DATE DATE NOT NULL
);
ALTER TABLE ACHIEVED_SESSION ADD CONSTRAINT PK_ACHIEVED_SESSION PRIMARY KEY (ID);
ALTER TABLE ACHIEVED_SESSION ADD CONSTRAINT UNIQUE_ACHIEVED_SESSION UNIQUE (BAGGER_NAME, TITLE);

COMMIT;